Update functions

diff --git a/home/.src/bash/utils/functions b/home/.src/bash/utils/functions
--- a/home/.src/bash/utils/functions
+++ b/home/.src/bash/utils/functions
@@ -164,3 +164,35 @@ function bash.utils.find_os_family() {
   # Detect Linux or Darwin
   printf "%s" "$(uname -s)"
 }
+
+#--------------------------------------------
+# FUNCTION: bash.utils.check_exit_status()
+# DESCRIPTION:
+# Check and handle exit status errors
+# check_exit_status $?
+# check_exit_status $? [SKIP/IGNORE]
+# Parameters: 
+#   $1, $?  - ($?)  Expands to the exit status
+#   $2, string - Ignore check if exit status is 1
+#--------------------------------------------
+function bash.utils.check_exit_status() {
+    exit_status=$1
+    test_skip=$2
+
+    if [ "${exit_status}" -ne 0 ]; then # test failed
+        if [ -n "${test_skip}" ]; then
+          # write test skip to files
+          printf "%s" '[CHECK EXIT STATUS]: Skipped [ OK ]'
+          return 
+        else
+          # ERROR: Caught a bad exit status.
+          # printf "%s" '[CHECK EXIT STATUS]: Status [ Failed ]'
+          # Could do error_cleanup here
+          exit $?
+        fi
+    fi
+    # printf "%s" '[CHECK EXIT STATUS]: Status [ OK ]'
+}
+
+# Export functions to other bash sub-shells
+# typeset -fx bash.utils.check_exit_status
